# Generated by Django 4.2.30 on 2026-09-23 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('grade', models.CharField(choices=[('BAC_MATH', 'باكالوريا رياضيات'), ('BAC_INFO', 'باكالوريا علوم الإعلامية'), ('BAC_SC', 'باكالوريا علوم تجريبية'), ('9TH_GRADE', 'التاسعة أساسي (نوفيام)')], default='BAC_MATH', max_length=20)),
                ('subject', models.CharField(default='عام', max_length=100)),
                ('file', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('chunk_index', models.IntegerField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='documents.document')),
            ],
        ),
    ]
