# Generated by Django 4.2.30 on 2026-09-23 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='🏆', max_length=10)),
                ('xp_required', models.PositiveIntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_level', models.CharField(choices=[('7_BASIC', '7ème Année Base (7 أساسي)'), ('8_BASIC', '8ème Année Base (8 أساسي)'), ('9_BASIC', '9ème Année Base (9 أساسي - النوفيام)'), ('1_SEC', '1ère Année Secondaire (1 ثانوي)'), ('2_SEC', '2ème Année Secondaire (2 ثانوي)'), ('3_SEC', '3ème Année Secondaire (3 ثانوي)'), ('BAC', 'Baccalauréat (الباكالوريا)')], default='BAC', max_length=20)),
                ('xp_points', models.PositiveIntegerField(default=0)),
                ('level', models.PositiveIntegerField(default=1)),
                ('streak_days', models.PositiveIntegerField(default=0)),
                ('last_activity', models.DateField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.badge')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='gamification.studentprofile')),
            ],
            options={
                'unique_together': {('student', 'badge')},
            },
        ),
    ]
